spring:
  datasource:
    url: jdbc:mysql://lrj_db.youyinian.cn/lrj_db?characterEncoding=utf8&autoReconnect=true
    username: valentine
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    common-entity: cn.valentine.entity.common
    app-entity: cn.valentine.entity.wechat
    common-repository: cn.valentine.repository.common
    app-repository: cn.valentine.repository.wechat
  jpa:
    show-sql: true